config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :games do
    collection do
      get 'search'
    end
      resources :reviews, except: [:show, :index]
  end

  root 'games#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord

  belongs_to :user
  has_many :reviews

has_attached_file :image, styles: { medium: "250x350#" }
validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :games
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]



  def index
    @games = Game.all
  end


  def show
    @review = Review.where(game_id: @game.id).order("created_at DESC")

    unless @reviews.present?
      @avg_review = 0
    else
      @avg_review = @reviews.average(:rating).present? ? @reviews.average(:rating).round(2) : 0
    end
  end


  def new
    @game = current_user.games.build
  end


  def edit
  end


  def create
    @game = current_user.games.build(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_path, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:title, :developer, :genre, :description, :release_date, :rating, :image, :link, :link_2, :link_3 )
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_game
  before_action :authenticate_user!


  def new
    @review = Review.new
  end


  def edit
  end


  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.game_id = @game.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to @game, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end



  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @game = Review.find(params[:id])
    end

    def set_game
      @game = Game.find(params[:game_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/games/_carousel.html.erb
<!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img class="first-slide" src="<%= @game.link %>" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              <h1 class="carousel-gameplay"><%= @game.title %>: Gameplay 1</h1>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="second-slide" src="<%= @game.link_2 %>" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1 class="carousel-gameplay"><%= @game.title %>: Gameplay 2</h1>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="third-slide" src="<%= @game.link_3 %>" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h1 class="carousel-gameplay"><%= @game.title %>: Gameplay 3</h1>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->

app/views/games/_form.html.erb
<%= bootstrap_form_for @game, html: { multipart: true } do |f| %>
<% if @game.errors.any? %>
<div id="error_explanation">
  <h2 class="page-title"><%= pluralize(track.errors.count, "error") %>
    prohibited this track from being saved:</h2>

  <ul>
    <% track.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<header class="formpage">
  <div class="row">
    <div class="newGameForm">
      <div class="panel panel-default">
        <div class="panel-heading">Game</div>
      </div>
      <div class="panel-body">
        <div class="formfield">
          <%= f.text_field :title, autofocus: true, placeholder: "Enter Title" %>
        </div>

        <div class="formfield">
          <%= f.text_field :developer, autofocus: true, placeholder: "Enter Developer"  %>
        </div>

        <div class="formfield">
          <%= f.text_field :genre, autofocus: true, placeholder: "Enter Genre"  %>
        </div>

        <div class="formfield">
          <%= f.text_area :description, autofocus: true, placeholder: "Enter Description"  %>
        </div>

        <div class="formfield">
          <%= f.text_field :release_date, autofocus: true, placeholder: "Enter Release Date"  %>
        </div>

        <div class="formfield">
          <%= f.text_field :rating, autofocus: true, placeholder: "Enter Rating"  %>
        </div>

        <div class="formfield">
          <%= f.text_field :link, autofocus: true, placeholder: "Link to Image (via online)"  %>
        </div>
        <div class="formfield">
          <%= f.text_field :link_2, autofocus: true, placeholder: "Link to Image (via online)"  %>
        </div>
        <div class="formfield">
          <%= f.text_field :link_3, autofocus: true, placeholder: "Link to Image (via online)"  %>
        </div>
        <div class="formfield">
          <%= f.file_field :image, autofocus: true %>
        </div>

        <div class="actions">
          <%= f.submit "Update Game", class: "btn btn-sp"%>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</header>
<p class="show-button">
  <%= link_to 'Back', games_path, class: "btn btn-sp", method: :get %>
</p>

app/views/games/edit.html.erb
<header class="formpage">
  <div class="row">
    <div class="panel-body">
      <img class="logo-heading-form2">
        <%= image_tag @game.image.url(:medium) %>
      </img>
    </header>
    <div class="panel-body">
      <%= render 'form', game: @game %>
      <%= button_to "Delete Game", game_path(@game), data: { confirm: "Are you sure that you to delete this game?" }, method: :delete, class: "btn btn-sp" %>
    </div>
  </div>
</div>
</header>

app/views/games/index.html.erb
<header class="intro">
  <div class="intro-body">
    <div class="container">
      <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
          <img class="logo-heading"><%= image_tag("Logo SP.svg", alt: "logo-img", height: 720, width: 720) %></img>
        </div>
        <% @games.each do |game| %>
        <div class="col-xs-6 col-sm-3 col-md-3 col-lg-3">
          <div class="thumbnail">
            <%= link_to (image_tag game.image.url(:medium), class: 'image animsition'), game, method: :get %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</header>

<% if user_signed_in? %>
<% else %>
<div class="jumbotron-inverse">
  <p class="jumbo-info">This is a place of digital nastalgia. If you've ever played the Sega Genesis (and loved it), you will absolutely love this website. Please feel free to create an account and add as many games as you want to the collection.</p>
  <p class="jumbo-button">
    <%= link_to "Sign Up To Add A Game", new_user_registration_path, class: "btn btn-sp btn-lg" %>
  </p>
</div>
<% end %>

<footer class="footer">
  <div class="container">
    <span class="text-muted">
      <a href="https://github.com/murphym757/sega_fansite"><%= image_tag("github.png", alt: "png-img", height: 100, width: 180) %></a>
      <a href="https://mauricemurphyjr.herokuapp.com/"><%= image_tag("mmlogo2.png", alt: "png-img", height: 80, width: 160) %></a><br>Copyright &copy; 2017<br></span>
  </div>
</footer>

app/views/games/new.html.erb
<%= render 'form', track: @game %>

<div class="container">
  <header class="formpage">
    <div class="row"></div>
  </header>
</div>

app/views/games/search.html.erb
<div class="row">
  <% @games.each do |game| %>
  <div class="col-xs-6 col-md-3">
    <div class="thumbnail">
      <%= link_to (image_tag game.image.url(:medium), class: 'image'), game %>
    </div>
  </div>
  <% end %>
</div>

app/views/games/show.html.erb
<div class="panel panel-default">
  <div class="panel-body animsition">
    <div class="row">
      <div class="col-md-4">
        <%= image_tag @game.image.url(:medium) %>
        <div class="star-rating" data-score=<%= @avg_review %>></div>
        <em><%= "#{@review.length} reviews" %></em>
        <div class="table-responsive">
          <table class="table">
            <tbody>
              <tr>
                <td>
                  <strong>Title:</strong>
                </td>
                <td class="game-title"><%= @game.title %></td>
              </tr>
              <tr>
                <td>
                  <strong>Developer:</strong>
                </td>
                <td class="developer-title"><%= @game.developer %></td>
              </tr>
              <tr>
                <td>
                  <strong>Genre:</strong>
                </td>
                <td><%= @game.genre %></td>
              </tr>
              <tr>
                <td>
                  <strong>Release date:</strong>
                </td>
                <td><%= @game.release_date %></td>
              </tr>
              <tr>
                <td>
                  <strong>Rating:</strong>
                </td>
                <td><%= @game.rating %></td>
              </tr>

            </tbody>
          </table>
        </div>
      </div>
      <div class="review-section">
        <div class"col-md-7 col-md-offset-1">
          <h1 class="review_title">Synopsis of
            <i>"<%= @game.title %>"</i>:</h1>
          <p><%= @game.description %></p>

          <% if @review.blank? %>
          <h3>It looks like no one's reviewed this game yet. Would you like to give the first review?</h3>
          <%= link_to "Write a Review", new_game_review_path(@game), class: "btn btn-sp" %>
        <% else %>
          <% @review.each do |review| %>
          <div class="reviews">
            <div class="star-rating" data-score=<%= review.rating %>></div>
            <p>
              <i><%= review.comment %></i>
            </p>
          </div>
          <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="game-carousel">
      <%= render 'games/carousel' %>
    </div>
  </div>

  <script>
    $('.star-rating').raty({
      starOn: '<%= image_path('star-on.png') %>',
      starOff: '<%= image_path('star-off.png') %>',
      path: '',
      readOnly: true,
      score: function () {
        return $(this).attr('data-score');
      }
    });
  </script>

  <nav aria-label="...">
    <p class="show-button">
      <%= link_to 'Edit', edit_game_path(@game), class: "btn btn-sp" %>
      <%= link_to 'Back', games_path, class: "btn btn-sp", method: :get %>
    </p>
  </nav>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="#">
        <%= link_to root_path, class: "navbar-brand animsition-link", method: :get do %>
        <i class="fa fa-home fa-lg" aria-hidden="true"></i>
        <% end %>
      </a>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li><%= link_to "New Game", new_game_path, class: "active" %></li>
        <li><%= link_to "Account", edit_user_registration_path, method: :get %></li>
      <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path, class: "active", method: :get %></li>
        <li><%= link_to "Sign In", new_user_session_path, class: "active", method: :get %></li>
        <% end %>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Maurice Murphy">
    <%= favicon_link_tag 'SPIcon.png' %>

    <title>Sega Paradise</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    <% flash.each do |name, msg| %>
        <% content_tag(:div, msg, class: "alert alert-info") %>
      <% end %>
      <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"
    			  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
    			  crossorigin="anonymous"></script>
    <%= javascript_include_tag 'animsition.min' %>
    <%= javascript_include_tag 'main' %>
    <%= javascript_include_tag 'jquery.raty' %>
    <%= javascript_include_tag 'bootstrap' %>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= bootstrap_form_for ([@game, @review]), html: { multipart: true } do |f| %>
<% if @game.errors.any? %>
<div id="error_explanation">
  <h2 class="page-title"><%= pluralize(track.errors.count, "error") %>
    prohibited this track from being saved:</h2>

  <ul>
    <% track.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<header class="formpage">
  <div class="row">
    <div class="newGameForm">
      <div class="panel panel-default">
        <div class="panel-heading">Game</div>
      </div>
      <div class="panel-body">
        <div class="field">
        <div id="star-rating"></div>
        </div>

        <div class="formfield">
          <%= f.text_area :comment, autofocus: true, placeholder: "How's the game"  %>
        </div>

        <div class="actions">
          <%= f.submit "Update Game", class: "btn btn-sp"%>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</header>
<p class="show-button">
  <%= link_to 'Back', games_path, class: "btn btn-sp", method: :get %>
</p>

<script>
$('#star-rating').raty({
  starOn: '<%= image_path('star-on.png') %>',
  starOff: '<%= image_path('star-off.png') %>',
  path: '',
scoreName: 'review[rating]'
});
</script>

app/views/reviews/edit.html.erb
<h2 class="page-title">Editing Review</h2>

<%= render 'form', review: @review %>


<div class="btn-group-vertical" role="group" aria-label="...">
  <ul class="pager">

    <li><%= link_to 'Back', game_path(@game) %></li>
  </ul>
</div>

app/views/reviews/new.html.erb
<h2 class="page-title">New Review</h2>

<%= render 'form', review: @review %>


<div class="btn-group-vertical" role="group" aria-label="...">
  <ul class="pager">
<li><%= link_to 'Back', game_path(@game) %></li>
  </ul>
</div>